### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jim-rosales** [mikeharrell16/bwui-capstone-placeholder#4]
Grade: Meets Expectations

Summary:
Hi Mike, congrats on finishing your capstone project and I hope your recovery continues to go well! Don't worry about not being able to implement accessibility features to the site. Whenever you have time, do consider adding these features to your capstone project as its excellent practice.

Overall though you did an excellent job as I loved the color scheme you chose and the hover effects you added. Your site was also responsive as it adapted to every width I tested it in so great job there as well!

I did open some issues that are meant as feedback as I'm sure you would have corrected them if you had the time and were in better condition. 

Do consider going over the attached zip that has a solution for the project to compare and contrast your implementation for the project with the given one. 

If you'd like to improve your project some more consider researching and making use of [variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables).  Variables are a great tool that allows you to enhance the readability of your project while making it easier to make changes to your stylesheet.

**Comment by mikeharrell16** [comment]
Hi Jim, thanks for the kind words. I will definitely do my best to go back and keep adding to my project to hone my skills. I have to say that I have already begun to utilize aspects of the course in page designs I am working on currently. I have found the CSS grid to be very beneficial in responsive design coding as it has dramatically cut down the time it takes to make the pages responsive for each screen size.

I did not see an attached zip file with a solution. I would love to review and compare to my design. If you could let me know how to access that zip file that would be great.

Thank you,
Mike Harrell

**Comment by jim-rosales** [comment]
Hello Mike,

Glad to hear that you've found the content in the cohort beneficial! As for the zip file to do apologize as I forgot to upload it.

Here you go:
[ware-house.zip](https://github.com/mikeharrell16/bwui-capstone-placeholder/files/1905998/ware-house.zip)
